# Generated by Django 4.2 on 2023-04-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=255, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=255, verbose_name="Last Name"),
                ),
                ("date_of_birth", models.DateField(verbose_name="Date of Birth")),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Phone Number"),
                ),
                ("email", models.EmailField(max_length=255, verbose_name="Email")),
                (
                    "registration_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registration Date"
                    ),
                ),
                (
                    "active_membership",
                    models.BooleanField(
                        default=False, verbose_name="Active Membership"
                    ),
                ),
                (
                    "membership_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Membership Start Date"
                    ),
                ),
                (
                    "membership_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Membership End Date"
                    ),
                ),
                (
                    "membership_cancellation_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Membership Cancellation Date",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
    ]
