# Generated by Django 4.2 on 2023-04-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitnessmanager_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "Cliente", "verbose_name_plural": "Clientes"},
        ),
        migrations.AddField(
            model_name="customer",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="customer_profile_pictures",
                verbose_name="Profile Picture",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="active_membership",
            field=models.BooleanField(default=False, verbose_name="Membresía Activa"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Dirección"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="date_of_birth",
            field=models.DateField(verbose_name="Fecha de Nacimiento"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=255, verbose_name="Correo Electrónico"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(max_length=255, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(max_length=255, verbose_name="Apellido"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="membership_cancellation_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Fin de Membresía"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="membership_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Fin de Membresía"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="membership_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Inicio de Membresía"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notas"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(max_length=20, verbose_name="Número de Teléfono"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="registration_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de Registro"
            ),
        ),
    ]
