# Generated by Django 4.2 on 2023-06-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessmanager_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Message', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterField(
            model_name='gymmembership',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='gymmembership',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
