# Generated by Django 4.2 on 2023-04-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fitnessmanager_api",
            "0002_alter_customer_options_customer_profile_picture_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="customer_profile_pictures",
                verbose_name="Foto",
            ),
        ),
    ]
