# Generated by Django 4.2 on 2023-05-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessmanager_api', '0002_message_messagecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
