# Generated by Django 4.2 on 2023-04-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessmanager_api', '0003_alter_customer_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Amount Paid'),
        ),
        migrations.AddField(
            model_name='customer',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Discount Percent'),
        ),
        migrations.AddField(
            model_name='customer',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Payment Date'),
        ),
        migrations.AddField(
            model_name='customer',
            name='passport_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Passport Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='customer',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight'),
        ),
    ]
