# Generated by Django 4.2 on 2023-04-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessmanager_api', '0004_customer_amount_paid_customer_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Cantidad Pagada'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de Descuento'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='passport_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DNI, NIE, N° de pasaporte'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso'),
        ),
    ]
