# Generated by Django 4.2 on 2023-04-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessmanager_api', '0005_alter_customer_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del último pago'),
        ),
    ]
