# Generated by Django 4.2 on 2023-05-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessmanager_api', '0006_alter_message_receiver_alter_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted_by_recepient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
    ]
