# Generated by Django 4.2 on 2023-04-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessmanager_api', '0006_alter_customer_last_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='membership_cancellation_date',
        ),
    ]
