# Generated by Django 4.2 on 2023-04-30 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessmanager_api', '0007_remove_customer_membership_cancellation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_payment_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='payment_method',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Cantidad Pagada')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de Descuento')),
                ('payment_method', models.CharField(blank=True, max_length=255, null=True, verbose_name='Método de Pago')),
                ('paid_month', models.PositiveIntegerField(verbose_name='Paid Month')),
                ('paid_year', models.PositiveIntegerField(verbose_name='Paid Year')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fitnessmanager_api.customer')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
