# Generated by Django 4.2 on 2023-04-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessmanager_api', '0008_remove_customer_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Método de Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_month',
            field=models.PositiveIntegerField(verbose_name='Mes Pagado'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_year',
            field=models.PositiveIntegerField(verbose_name='Año Pagado'),
        ),
    ]
