# Generated by Django 4.2 on 2023-04-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessmanager_api', '0009_alter_payment_options_alter_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
    ]
