# Generated by Django 4.2 on 2023-05-29 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessmanager_api', '0009_conversation_created_at_conversation_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
