# Generated by Django 4.2 on 2023-04-30 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessmanager_api', '0010_alter_payment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Customers'},
        ),
    ]
