# Generated by Django 4.2 on 2023-04-30 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessmanager_api', '0011_alter_customer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fitnessmanager_api.customer', verbose_name='Cliente'),
        ),
    ]
