# Generated by Django 4.2 on 2023-04-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessmanager_api', '0012_alter_payment_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_month',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], verbose_name='Mes Pagado'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_year',
            field=models.PositiveIntegerField(choices=[(2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031'), (2032, '2032'), (2033, '2033'), (2034, '2034'), (2035, '2035'), (2036, '2036'), (2037, '2037'), (2038, '2038'), (2039, '2039'), (2040, '2040'), (2041, '2041'), (2042, '2042')], verbose_name='Año Pagado'),
        ),
    ]
