# Generated by Django 4.2 on 2023-05-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessmanager_api', '0013_alter_customer_options_alter_payment_paid_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='replacemewithhashedpassword', max_length=128),
            preserve_default=False,
        ),
    ]
