# Generated by Django 4.2 on 2023-05-06 23:58

from django.db import migrations, models
import fitnessmanager_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessmanager_api', '0014_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default=fitnessmanager_api.models.generate_password, max_length=128),
        ),
    ]
